### ISSUE TITLE
Last updataed some problem

### ISSUE THREAD

**Issue by tssailzz8** [kalilistic/neat-plugins-plus#8]
![image](https://user-images.githubusercontent.com/52206101/156085934-b01fd257-c0cd-4fc9-8c1e-35b3294cf518.png)
![image](https://user-images.githubusercontent.com/52206101/156085980-cc026e1f-cdac-4173-9e5a-a21433a26318.png)
it not true

**Comment by kalilistic** [comment]
This is due to the github api updated_at field can be updated by other changes to the repository like changing a description or setting and not just commits.

https://api.github.com/repos/daemitus/YesAlready
"updated_at": "2022-02-28T08:27:10Z",

The date/time you highlighted is the last commit which is a separate endpoint. I tried using this originally but it's a separate endpoint which is a pain due to github's severe rate limiting.

Although, looking now.... at least in this case the pushed_at matches the last commit. I'll need to compare some other repos but I wonder if I could use this instead of updated_at.
"pushed_at": "2022-01-29T03:49:32Z",

**Comment by kalilistic** [comment]
I switched to pushed_at... let me know what you think. I see one or two that are a little odd but seems better. I'll consider other ways to use the commit endpoint.

**Comment by tssailzz8** [comment]
I just want to know who recently updated the code

**Comment by kalilistic** [comment]
bah, thanks github. I'll look at this more today.

**Comment by kalilistic** [comment]
Okay, seems to be working now and matches the last commit. Let me know if looks good to you.
